import React from 'react';
import { 
  Droplets, 
  Zap, 
  Flame, 
  Wifi, 
  Trash2, 
  Fan, 
  ArrowUpDown, 
  Gauge,
  Bolt,
  Thermometer,
  Wrench,
  Settings,
  Home,
  Building2,
  Sun,
  Cloud,
  CloudRain,
  Snowflake,
  Wind,
  Leaf,
  Trees,
  Car,
  Bike,
  Bus,
  Train,
  Plane,
  Ship,
  Anchor,
  Compass,
  MapPin,
  Navigation,
  Target,
  Crosshair,
  Shield,
  Lock,
  Unlock,
  Key,
  Bell,
  AlertTriangle,
  Info,
  HelpCircle,
  CheckCircle,
  XCircle,
  MinusCircle,
  PlusCircle,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  X,
  Check,
  Plus,
  Minus,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  Calendar,
  Clock,
  Watch,
  Timer,
  History,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Download,
  Upload,
  Share,
  Link,
  ExternalLink,
  Copy,
  Scissors,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  Folder,
  FolderOpen,
  Save,
  Edit,
  Edit3,
  Pencil,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  ListOrdered,
  Quote,
  Code,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Printer,
  Camera,
  Video,
  Mic,
  Headphones,
  Speaker,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat,
  Repeat1,
  Music,
  Radio,
  Tv,
  Gamepad2,
  Mouse,
  Keyboard
} from 'lucide-react';

interface IconSelectorProps {
  isOpen: boolean;
  onClose: () => void;
  onSelect: (icon: React.ReactNode) => void;
  currentIcon?: React.ReactNode;
}

const AVAILABLE_ICONS = [
  { name: 'Vanduo', icon: <Droplets className="w-4 h-4" /> },
  { name: 'Žaibas', icon: <Zap className="w-4 h-4" /> },
  { name: 'Ugnis', icon: <Flame className="w-4 h-4" /> },
  { name: 'WiFi', icon: <Wifi className="w-4 h-4" /> },
  { name: 'Šiukšlės', icon: <Trash2 className="w-4 h-4" /> },
  { name: 'Vėdinimas', icon: <Fan className="w-4 h-4" /> },
  { name: 'Liftas', icon: <ArrowUpDown className="w-4 h-4" /> },
  { name: 'Skaitliukas', icon: <Gauge className="w-4 h-4" /> },
  { name: 'Elektra', icon: <Bolt className="w-4 h-4" /> },
  { name: 'Temperatūra', icon: <Thermometer className="w-4 h-4" /> },
  { name: 'Įrankiai', icon: <Wrench className="w-4 h-4" /> },
  { name: 'Nustatymai', icon: <Settings className="w-4 h-4" /> },
  { name: 'Namas', icon: <Home className="w-4 h-4" /> },
  { name: 'Pastatas', icon: <Building2 className="w-4 h-4" /> },
  { name: 'Saulė', icon: <Sun className="w-4 h-4" /> },
  { name: 'Debesis', icon: <Cloud className="w-4 h-4" /> },
  { name: 'Lietus', icon: <CloudRain className="w-4 h-4" /> },
  { name: 'Sniegas', icon: <Snowflake className="w-4 h-4" /> },
  { name: 'Vėjas', icon: <Wind className="w-4 h-4" /> },
  { name: 'Lapas', icon: <Leaf className="w-4 h-4" /> },
  { name: 'Medis', icon: <Trees className="w-4 h-4" /> },
  { name: 'Automobilis', icon: <Car className="w-4 h-4" /> },
  { name: 'Dviratis', icon: <Bike className="w-4 h-4" /> },
  { name: 'Autobusas', icon: <Bus className="w-4 h-4" /> },
  { name: 'Traukinys', icon: <Train className="w-4 h-4" /> },
  { name: 'Lėktuvas', icon: <Plane className="w-4 h-4" /> },
  { name: 'Laivas', icon: <Ship className="w-4 h-4" /> },
  { name: 'Inkaro', icon: <Anchor className="w-4 h-4" /> },
  { name: 'Kompasas', icon: <Compass className="w-4 h-4" /> },
  { name: 'Žemėlapis', icon: <MapPin className="w-4 h-4" /> },
  { name: 'Navigacija', icon: <Navigation className="w-4 h-4" /> },
  { name: 'Taikinys', icon: <Target className="w-4 h-4" /> },
  { name: 'Kryžius', icon: <Crosshair className="w-4 h-4" /> },
  { name: 'Skydas', icon: <Shield className="w-4 h-4" /> },
  { name: 'Užraktas', icon: <Lock className="w-4 h-4" /> },
  { name: 'Atrakintas', icon: <Unlock className="w-4 h-4" /> },
  { name: 'Raktas', icon: <Key className="w-4 h-4" /> },
  { name: 'Skambutis', icon: <Bell className="w-4 h-4" /> },
  { name: 'Įspėjimas', icon: <AlertTriangle className="w-4 h-4" /> },
  { name: 'Informacija', icon: <Info className="w-4 h-4" /> },
  { name: 'Pagalba', icon: <HelpCircle className="w-4 h-4" /> },
  { name: 'Patvirtinta', icon: <CheckCircle className="w-4 h-4" /> },
  { name: 'Atmesta', icon: <XCircle className="w-4 h-4" /> },
  { name: 'Minus', icon: <MinusCircle className="w-4 h-4" /> },
  { name: 'Plius', icon: <PlusCircle className="w-4 h-4" /> },
  { name: 'Žvaigždė', icon: <Star className="w-4 h-4" /> },
  { name: 'Širdis', icon: <Heart className="w-4 h-4" /> },
  { name: 'Nykti', icon: <ThumbsUp className="w-4 h-4" /> },
  { name: 'Nenkti', icon: <ThumbsDown className="w-4 h-4" /> },
  { name: 'Šypsena', icon: <Smile className="w-4 h-4" /> },
  { name: 'Liūdnas', icon: <Frown className="w-4 h-4" /> },
  { name: 'Neutralus', icon: <Meh className="w-4 h-4" /> },
  { name: 'Uždaryti', icon: <X className="w-4 h-4" /> },
  { name: 'Patvirtinti', icon: <Check className="w-4 h-4" /> },
  { name: 'Pridėti', icon: <Plus className="w-4 h-4" /> },
  { name: 'Atimti', icon: <Minus className="w-4 h-4" /> },
  { name: 'Ieškoti', icon: <Search className="w-4 h-4" /> },
  { name: 'Filtruoti', icon: <Filter className="w-4 h-4" /> },
  { name: 'Rūšiuoti A-Ž', icon: <SortAsc className="w-4 h-4" /> },
  { name: 'Rūšiuoti Ž-A', icon: <SortDesc className="w-4 h-4" /> },
  { name: 'Kalendorius', icon: <Calendar className="w-4 h-4" /> },
  { name: 'Laikas', icon: <Clock className="w-4 h-4" /> },
  { name: 'Laikrodis', icon: <Watch className="w-4 h-4" /> },
  { name: 'Laikmatis', icon: <Timer className="w-4 h-4" /> },
  { name: 'Istorija', icon: <History className="w-4 h-4" /> },
  { name: 'Atnaujinti', icon: <RefreshCw className="w-4 h-4" /> },
  { name: 'Atgal', icon: <RotateCcw className="w-4 h-4" /> },
  { name: 'Pirmyn', icon: <RotateCw className="w-4 h-4" /> },
  { name: 'Atsisiųsti', icon: <Download className="w-4 h-4" /> },
  { name: 'Įkelti', icon: <Upload className="w-4 h-4" /> },
  { name: 'Dalintis', icon: <Share className="w-4 h-4" /> },
  { name: 'Nuoroda', icon: <Link className="w-4 h-4" /> },
  { name: 'Išorės nuoroda', icon: <ExternalLink className="w-4 h-4" /> },
  { name: 'Kopijuoti', icon: <Copy className="w-4 h-4" /> },
  { name: 'Iškirpti', icon: <Scissors className="w-4 h-4" /> },
  { name: 'Failas', icon: <File className="w-4 h-4" /> },
  { name: 'Tekstas', icon: <FileText className="w-4 h-4" /> },
  { name: 'Paveikslėlis', icon: <FileImage className="w-4 h-4" /> },
  { name: 'Video', icon: <FileVideo className="w-4 h-4" /> },
  { name: 'Garsas', icon: <FileAudio className="w-4 h-4" /> },
  { name: 'Aplankas', icon: <Folder className="w-4 h-4" /> },
  { name: 'Atidarytas aplankas', icon: <FolderOpen className="w-4 h-4" /> },
  { name: 'Išsaugoti', icon: <Save className="w-4 h-4" /> },
  { name: 'Redaguoti', icon: <Edit className="w-4 h-4" /> },
  { name: 'Redaguoti 2', icon: <Edit3 className="w-4 h-4" /> },
  { name: 'Pieštukas', icon: <Pencil className="w-4 h-4" /> },
  { name: 'Tekstas', icon: <Type className="w-4 h-4" /> },
  { name: 'Paryškinti', icon: <Bold className="w-4 h-4" /> },
  { name: 'Pasviręs', icon: <Italic className="w-4 h-4" /> },
  { name: 'Pabraukti', icon: <Underline className="w-4 h-4" /> },
  { name: 'Perbraukti', icon: <Strikethrough className="w-4 h-4" /> },
  { name: 'Kairė', icon: <AlignLeft className="w-4 h-4" /> },
  { name: 'Centras', icon: <AlignCenter className="w-4 h-4" /> },
  { name: 'Dešinė', icon: <AlignRight className="w-4 h-4" /> },
  { name: 'Išlygiuoti', icon: <AlignJustify className="w-4 h-4" /> },
  { name: 'Sąrašas', icon: <List className="w-4 h-4" /> },
  { name: 'Numeruotas sąrašas', icon: <ListOrdered className="w-4 h-4" /> },
  { name: 'Citata', icon: <Quote className="w-4 h-4" /> },
  { name: 'Kodas', icon: <Code className="w-4 h-4" /> },
  { name: 'Terminalas', icon: <Terminal className="w-4 h-4" /> },
  { name: 'Duomenų bazė', icon: <Database className="w-4 h-4" /> },
  { name: 'Serveris', icon: <Server className="w-4 h-4" /> },
  { name: 'Kietasis diskas', icon: <HardDrive className="w-4 h-4" /> },
  { name: 'Turbo', icon: <Cpu className="w-4 h-4" /> },
  { name: 'Atmintis', icon: <MemoryStick className="w-4 h-4" /> },
  { name: 'Monitorius', icon: <Monitor className="w-4 h-4" /> },
  { name: 'Telefonas', icon: <Smartphone className="w-4 h-4" /> },
  { name: 'Planšetė', icon: <Tablet className="w-4 h-4" /> },
  { name: 'Nešiojamas', icon: <Laptop className="w-4 h-4" /> },
  { name: 'Spausdintuvas', icon: <Printer className="w-4 h-4" /> },
  { name: 'Kamera', icon: <Camera className="w-4 h-4" /> },
  { name: 'Video kamera', icon: <Video className="w-4 h-4" /> },
  { name: 'Mikrofonas', icon: <Mic className="w-4 h-4" /> },
  { name: 'Ausinės', icon: <Headphones className="w-4 h-4" /> },
  { name: 'Garsiakalbis', icon: <Speaker className="w-4 h-4" /> },
  { name: 'Garsas', icon: <Volume className="w-4 h-4" /> },
  { name: 'Garsas 1', icon: <Volume1 className="w-4 h-4" /> },
  { name: 'Garsas 2', icon: <Volume2 className="w-4 h-4" /> },
  { name: 'Išjungti garsą', icon: <VolumeX className="w-4 h-4" /> },
  { name: 'Groti', icon: <Play className="w-4 h-4" /> },
  { name: 'Pauzė', icon: <Pause className="w-4 h-4" /> },
  { name: 'Atgal', icon: <SkipBack className="w-4 h-4" /> },
  { name: 'Pirmyn', icon: <SkipForward className="w-4 h-4" /> },
  { name: 'Atvynioti', icon: <Rewind className="w-4 h-4" /> },
  { name: 'Greitai pirmyn', icon: <FastForward className="w-4 h-4" /> },
  { name: 'Maišyti', icon: <Shuffle className="w-4 h-4" /> },
  { name: 'Kartoti', icon: <Repeat className="w-4 h-4" /> },
  { name: 'Kartoti 1', icon: <Repeat1 className="w-4 h-4" /> },
  { name: 'Muzika', icon: <Music className="w-4 h-4" /> },
  { name: 'Radijas', icon: <Radio className="w-4 h-4" /> },
  { name: 'TV', icon: <Tv className="w-4 h-4" /> },
  { name: 'Žaidimų pultas', icon: <Gamepad2 className="w-4 h-4" /> },
  { name: 'Pelė', icon: <Mouse className="w-4 h-4" /> },
  { name: 'Klaviatūra', icon: <Keyboard className="w-4 h-4" /> }
];

export const IconSelector: React.FC<IconSelectorProps> = ({
  isOpen,
  onClose,
  onSelect,
  currentIcon
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-2">
      <div className="bg-white rounded-lg shadow-xl max-w-xl w-full max-h-[70vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-2 border-b border-gray-200">
          <h2 className="text-sm font-semibold text-gray-900">Pasirinkite ikoną</h2>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-100 rounded transition-colors"
          >
            <X className="w-3 h-3 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-2 overflow-y-auto max-h-[calc(70vh-60px)]">
          <div className="grid grid-cols-8 gap-1">
            {AVAILABLE_ICONS.map((iconItem, index) => (
              <button
                key={index}
                onClick={() => {
                  onSelect(iconItem.icon);
                  onClose();
                }}
                                  className={`p-1.5 rounded border transition-all duration-200 hover:bg-gray-50 hover:border-[#2F8481] flex flex-col items-center justify-center gap-0.5 ${
                    currentIcon && React.isValidElement(currentIcon) &&
                    React.isValidElement(iconItem.icon) &&
                    currentIcon.type === iconItem.icon.type
                      ? 'border-[#2F8481] bg-[#2F8481]/5'
                      : 'border-gray-200'
                  }`}
                  title={iconItem.name}
                >
                  <div className="w-3 h-3 flex items-center justify-center">
                    {React.cloneElement(iconItem.icon, { className: "w-3 h-3" })}
                  </div>
                  <span className="text-xs text-gray-500 text-center leading-tight">{iconItem.name}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
