-- Fix Lithuanian characters in amenities table
-- First clear property_amenities (junction table)
DELETE FROM property_amenities;
DELETE FROM amenities;

-- Re-insert with correct UTF-8 encoding
INSERT INTO amenities (key, name, category, is_custom) VALUES
-- Kitchen
('fridge', 'Šaldytuvas', 'kitchen', false),
('stove', 'Viryklė', 'kitchen', false),
('oven', 'Orkaitė', 'kitchen', false),
('microwave', 'Mikrobangos', 'kitchen', false),
('dishwasher', 'Indaplovė', 'kitchen', false),
('kettle', 'Virdulys', 'kitchen', false),
('coffee_maker', 'Kavos aparatas', 'kitchen', false),
('espresso', 'Espreso aparatas', 'kitchen', false),
('toaster', 'Skrudintuvai', 'kitchen', false),
('freezer', 'Šaldiklis', 'kitchen', false),
('kitchen_utensils', 'Virtuvės reikmenys', 'kitchen', false),
('pots_pans', 'Puodai ir keptuvės', 'kitchen', false),
('dining_table', 'Valgomojo stalas', 'kitchen', false),
('blender', 'Blenderis', 'kitchen', false),
('food_processor', 'Virtuvinis kombainas', 'kitchen', false),
-- Appliances
('washing_machine', 'Skalbimo mašina', 'appliances', false),
('dryer', 'Džiovyklė', 'appliances', false),
('iron', 'Lygintuvas', 'appliances', false),
('ironing_board', 'Lyginimo lenta', 'appliances', false),
('vacuum', 'Dulkių siurblys', 'appliances', false),
('tv', 'Televizorius', 'appliances', false),
('smart_tv', 'Smart TV', 'appliances', false),
('air_conditioner', 'Kondicionierius', 'appliances', false),
('heater', 'Šildytuvas', 'appliances', false),
('fan', 'Ventiliatorius', 'appliances', false),
('hair_dryer', 'Plaukų džiovintuvas', 'appliances', false),
('gaming_console', 'Žaidimų konsolė', 'appliances', false),
('projector', 'Projektorius', 'appliances', false),
('sound_system', 'Garso sistema', 'appliances', false),
('electric_blinds', 'Elektrinės žaliuzės', 'appliances', false),
('dehumidifier', 'Drėgmės surinktuvas', 'appliances', false),
('air_purifier', 'Oro valytuvas', 'appliances', false),
('robot_vacuum', 'Robotas siurblys', 'appliances', false),
('electric_kettle', 'Elektrinis virdulys', 'appliances', false),
-- Building
('elevator', 'Liftas', 'building', false),
('intercom', 'Domofomas', 'building', false),
('video_intercom', 'Vaizdo domofomas', 'building', false),
('concierge', 'Konsjeržas', 'building', false),
('trash_chute', 'Šiukšlių vamzdis', 'building', false),
('recycling', 'Rūšiavimo konteineriai', 'building', false),
('postal_boxes', 'Pašto dėžutės', 'building', false),
('bike_storage', 'Dviračių saugykla', 'building', false),
('stroller_room', 'Vežimėlių kambarys', 'building', false),
('laundry_room', 'Skalbykla', 'building', false),
('gym', 'Sporto salė', 'building', false),
('sauna', 'Sauna', 'building', false),
('swimming_pool', 'Baseinas', 'building', false),
('playground', 'Vaikų žaidimų aikštelė', 'building', false),
('security', 'Apsauga', 'building', false),
('cctv', 'Vaizdo stebėjimas', 'building', false),
('fire_alarm', 'Priešgaisrinė signalizacija', 'building', false),
('wheelchair_access', 'Pritaikyta neįgaliesiems', 'building', false),
('broadband_internet', 'Šviesolaidinis internetas', 'building', false),
('underground_parking', 'Požeminė automobilių aikštelė', 'building', false),
('guest_parking', 'Svečių parkavimas', 'building', false),
('electric_car_charger', 'Elektromobilio įkrovimas', 'building', false),
('roof_terrace', 'Stogo terasa', 'building', false),
('common_garden', 'Bendras sodas', 'building', false),
('basement_storage', 'Rūsio sandėliukas', 'building', false),
-- Comfort
('wifi', 'WiFi', 'comfort', false),
('cable_tv', 'Kabelinė televizija', 'comfort', false),
('heating', 'Šildymas', 'comfort', false),
('floor_heating', 'Šildomos grindys', 'comfort', false),
('central_heating', 'Centrinis šildymas', 'comfort', false),
('gas_heating', 'Dujinis šildymas', 'comfort', false),
('fireplace', 'Židinys', 'comfort', false),
('electric_fireplace', 'Elektrinis židinys', 'comfort', false),
('balcony', 'Balkonas', 'comfort', false),
('terrace', 'Terasa', 'comfort', false),
('loggia', 'Lodžija', 'comfort', false),
('garden', 'Sodas', 'comfort', false),
('private_parking', 'Privati parkavimo vieta', 'comfort', false),
('garage', 'Garažas', 'comfort', false),
('storage_room', 'Sandėliukas', 'comfort', false),
('walk_in_closet', 'Drabužinė', 'comfort', false),
('bathtub', 'Vonia', 'comfort', false),
('shower', 'Dušas', 'comfort', false),
('jacuzzi', 'Džakuzė', 'comfort', false),
('bidet', 'Bidė', 'comfort', false),
('double_sink', 'Dviguba kriauklė', 'comfort', false),
('heated_towel_rail', 'Šildomas rankšluosčių laikiklis', 'comfort', false),
('underfloor_bathroom_heating', 'Vonios grindų šildymas', 'comfort', false),
('aromatherapy_diffuser', 'Aromaterapijos difuzorius', 'comfort', false),
-- Outdoor
('private_garden', 'Privatus sodas', 'outdoor', false),
('shared_garden', 'Bendras kiemas', 'outdoor', false),
('patio', 'Kiemo terasa', 'outdoor', false),
('bbq', 'Grilis', 'outdoor', false),
('outdoor_furniture', 'Lauko baldai', 'outdoor', false),
('swimming_pool_private', 'Privatus baseinas', 'outdoor', false),
('hot_tub', 'Karšto vandens kubas', 'outdoor', false),
('outdoor_shower', 'Lauko dušas', 'outdoor', false),
('hammock', 'Hamakas', 'outdoor', false),
('gazebo', 'Pavėsinė', 'outdoor', false),
('pergola', 'Pergolė', 'outdoor', false),
('outdoor_lighting', 'Lauko apšvietimas', 'outdoor', false),
('irrigation_system', 'Laistymo sistema', 'outdoor', false),
('fence', 'Tvora', 'outdoor', false),
('gate', 'Vartai', 'outdoor', false),
('carport', 'Automobilio stoginė', 'outdoor', false),
('vegetable_garden', 'Daržas', 'outdoor', false),
('greenhouse', 'Šiltnamis', 'outdoor', false),
('trampoline', 'Batutas', 'outdoor', false),
('sandbox', 'Smėlio dėžė', 'outdoor', false),
('balcony_furniture', 'Balkono baldai', 'outdoor', false),
('sun_loungers', 'Gultai', 'outdoor', false),
('parasol', 'Skėtis', 'outdoor', false);
